/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Paquete;
import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import java.text.Format;
import java.util.Date;
import java.util.Calendar;
import java.text.DateFormat;
import java.text.ParseException;
import javax.swing.JOptionPane;
/**
 *
 * @author Gloria Alicia
 */
public class ConsultaGastos extends javax.swing.JFrame {

    /**
     * Creates new form ConsultaGastos
     */
    public ConsultaGastos() {
        initComponents();
        this.getContentPane().setBackground(Color.WHITE);
        DefaultTableModel modelo=new DefaultTableModel();
        modelo.addColumn("Fecha");
        modelo.addColumn("Concepto");
        modelo.addColumn("Subtotal");
        modelo.addColumn("IVA");
        modelo.addColumn("Total");
        modelo.addColumn("Método de pago");
        tblCortes.setModel(modelo);
        String sql;
        ResultSet rs;
        Statement st;
        String[] datos=new String[6];
        
            sql="SELECT GASTO_FECHA, GASTOS_CONCEPTO, GASTOS_MONTO, GASTO_IVA, GASTO_TOTAL, GASTO_METODO"
                    + " FROM peleteriacid.gastos;";
        try {
            Format formatter = new SimpleDateFormat("yyyy-MM-dd");
            st=cn.createStatement();
            rs=st.executeQuery(sql);
            
            while (rs.next()){
                datos[0]=formatter.format(rs.getDate(1));
                datos[1]=rs.getString(2);
                datos[2]=String.valueOf(rs.getDouble(3));
                datos[3]=String.valueOf(rs.getDouble(4));
                datos[4]=String.valueOf(rs.getDouble(5));
                datos[5]=rs.getString(6);
                modelo.addRow(datos);
            }
            tblCortes.setModel(modelo);
            rs.close();
            
        }catch(SQLException ex){
            Logger.getLogger(Facturas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCortes = new javax.swing.JTable();
        btnListar = new javax.swing.JButton();
        dateFecha = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        dateFecha1 = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 204));
        jLabel9.setText("CONSULTA DE GASTOS");

        tblCortes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblCortes);

        btnListar.setText("Listar");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        jLabel1.setText("Escoja una fecha inicial:");

        jLabel2.setText("Escoja una fecha finall:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dateFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(181, 181, 181)
                                .addComponent(btnListar))
                            .addComponent(dateFecha1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(jLabel9))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(dateFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addComponent(btnListar))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dateFecha1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        Format formatter = new SimpleDateFormat("yyyy-MM-dd");
        String fecha=formatter.format(dateFecha.getDate());
        String fecha1=formatter.format(dateFecha1.getDate());
        DefaultTableModel modelo=new DefaultTableModel();
        modelo.addColumn("Fecha");
        modelo.addColumn("Concepto");
        modelo.addColumn("Subtotal");
        modelo.addColumn("IVA");
        modelo.addColumn("Total");
        modelo.addColumn("Método de pago");
        tblCortes.setModel(modelo);
        String sql;
        ResultSet rs;
        Statement st;
        String[] datos=new String[6];
        sql="SELECT GASTO_FECHA, GASTOS_CONCEPTO, GASTOS_MONTO, GASTO_IVA, GASTO_TOTAL, GASTO_METODO"
        + " FROM peleteriacid.gastos WHERE GASTO_FECHA BETWEEN '"+fecha+"' AND '"+fecha1+"';";
        try {
            st=cn.createStatement();
            rs=st.executeQuery(sql);
            System.out.println(sql);
            while (rs.next()){
                datos[0]=formatter.format(rs.getDate(1));
                datos[1]=rs.getString(2);
                datos[2]=String.valueOf(rs.getDouble(3));
                datos[3]=String.valueOf(rs.getDouble(4));
                datos[4]=String.valueOf(rs.getDouble(5));
                datos[5]=rs.getString(6);
                modelo.addRow(datos);
            }
            tblCortes.setModel(modelo);
            rs.close();

        }catch(SQLException ex){
            Logger.getLogger(Facturas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnListarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaGastos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaGastos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaGastos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaGastos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaGastos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnListar;
    private com.toedter.calendar.JDateChooser dateFecha;
    private com.toedter.calendar.JDateChooser dateFecha1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCortes;
    // End of variables declaration//GEN-END:variables
Conectar cc=new Conectar();
Connection cn=cc.conexion();
}
