/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Paquete;

/**
 *
 * @author Gloria
 */
public class CorteCajaMes extends javax.swing.JFrame {

    /**
     * Creates new form CorteCajaMes
     */
    public CorteCajaMes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCorte = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbGastofijo = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblGastos = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        cmbGastos = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTabla = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCorte.setText("Hacer corte del dia");
        btnCorte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCorteActionPerformed(evt);
            }
        });

        jLabel1.setText("Pedidos del dia:");

        jLabel2.setText("Gastos:");

        cmbGastofijo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Agregar gasto Fijo>" }));
        cmbGastofijo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbGastofijoActionPerformed(evt);
            }
        });

        tblGastos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblGastos);

        cmbGastos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Agregar gasto Variable>" }));
        cmbGastos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbGastosActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 204));
        jLabel9.setText("CORTE DEL DIA");

        tblTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblTabla);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(185, 185, 185)
                        .addComponent(jLabel9)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCorte))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmbGastofijo, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(cmbGastos, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(6, 6, 6)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbGastos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbGastofijo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCorte, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCorteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCorteActionPerformed
/*
        int rows=modelo.getRowCount(), i=0;
        int rows1=modelo1.getRowCount();
        Double Total=0.0, Monto=0.0;
        String[] Conceptos=new String [rows1];
        Double[] Montos=new Double [rows1];
        int[] IDs=new int [rows];
        while(i<rows1){
            String concepto=tblGastos.getValueAt(i, 0).toString();
            Conceptos[i]=concepto;
            Monto+=Double.parseDouble(tblGastos.getValueAt(i, 2).toString());
            i++;
        }
        i=0;
        while(i<rows){
            IDs[i]=Integer.parseInt(tblTabla.getValueAt(i, 0).toString());
            Total+=Double.parseDouble(tblTabla.getValueAt(i, 1).toString());
            System.out.println(Total);
            i++;
        }

        try{
            Date fecha = new Date();
            DateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
            Date utilDate = new SimpleDateFormat("dd-MM-yyyy").parse(dateFormat.format(fecha));
            java.sql.Date sqlDate = new java.sql.Date(utilDate.getTime());
            PreparedStatement pst =cn.prepareStatement("INSERT INTO peleteriacid.cortecaja_dias(CORTEDIA_FECHA, CORTEDIA_INGRESOS, CORTEDIA_EGRESOS, CORTEDIA_MONTOTOTAL)"
                +" VALUES ( ?, ?, ?, ?);");
            pst.setDate(1, sqlDate);
            pst.setDouble(2, Total);
            pst.setDouble(3, Monto);
            pst.setDouble(4, Total-Monto);
            System.out.println(pst);
            pst.executeUpdate();
        }catch(SQLException ex){
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }catch (ParseException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        i=0;
        while(i<rows1){
            String GastoID="";
            String sql;
            ResultSet rs;
            Statement st;
            String[] datos=new String[1];
            sql="SELECT GASTOS_ID"
            + " FROM peleteriacid.gastos WHERE GASTOS_CONCEPTO = '"+Conceptos[i]+"';";
            try {
                st=cn.createStatement();
                rs=st.executeQuery(sql);

                while (rs.next()){
                    GastoID=Integer.toString(rs.getInt(1));
                }
                rs.close();
                System.out.println("Id del gasto con el concepto "+Conceptos[i]+" es: "+GastoID);
            }catch(SQLException ex){
                Logger.getLogger(RegistrarVenta.class.getName()).log(Level.SEVERE, null, ex);
            }
            int ID=Integer.parseInt(GastoID);
            try{
                Date fecha = new Date();
                DateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
                Date utilDate = new SimpleDateFormat("dd-MM-yyyy").parse(dateFormat.format(fecha));
                java.sql.Date sqlDate = new java.sql.Date(utilDate.getTime());
                PreparedStatement pst =cn.prepareStatement("INSERT INTO peleteriacid.cortecaja_dias_has_gastos(CORTEDIA_FECHA, GASTOS_ID)"
                    +" VALUES ( ?, ?);");
                pst.setDate(1, sqlDate);
                pst.setInt(2, ID);
                System.out.println(pst);
                pst.executeUpdate();
            }catch(SQLException ex){
                Logger.getLogger(AgregarMaterial.class.getName()).log(Level.SEVERE, null, ex);
            }catch (ParseException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            }
            i++;
        }
        i=0;
        while(i<rows){
            try{
                Date fecha = new Date();
                DateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
                Date utilDate = new SimpleDateFormat("dd-MM-yyyy").parse(dateFormat.format(fecha));
                java.sql.Date sqlDate = new java.sql.Date(utilDate.getTime());
                PreparedStatement pst =cn.prepareStatement("INSERT INTO peleteriacid.pedidos_has_cortecaja_dias(PEDIDO_ID,CORTEDIA_FECHA)"
                    +" VALUES ( ?, ?);");
                pst.setInt(1, IDs[i]);
                pst.setDate(2, sqlDate);
                System.out.println(pst);
                pst.executeUpdate();
            }catch(SQLException ex){
                Logger.getLogger(AgregarMaterial.class.getName()).log(Level.SEVERE, null, ex);
            }catch (ParseException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            }
            i++;
        }
        JOptionPane.showMessageDialog(this, "Corte del día generado");*/
    }//GEN-LAST:event_btnCorteActionPerformed

    private void cmbGastofijoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbGastofijoActionPerformed
       /* String Concepto=cmbGastofijo.getSelectedItem().toString();
        String Tipo="", Descripcion="", Monto="";
        String sql;
        String[] datos=new String[4];
        ResultSet rs;
        Statement st;
        sql="SELECT GASTOS_TIPO, GASTOS_MONTO, GASTOS_DESCRIPCION "
        + " FROM peleteriacid.gastos WHERE GASTOS_CONCEPTO = '"+Concepto+"';";
        try {
            st=cn.createStatement();
            rs=st.executeQuery(sql);

            while (rs.next()){
                datos[0]=Concepto;
                datos[1]=rs.getString(1);
                datos[2]=String.valueOf(rs.getDouble(2));
                datos[3]=rs.getString(3);
            }
            rs.close();
            modelo1.addRow(datos);
            tblGastos.setModel(modelo1);
        }catch(SQLException ex){
            Logger.getLogger(RegistrarVenta.class.getName()).log(Level.SEVERE, null, ex);
        }*/
    }//GEN-LAST:event_cmbGastofijoActionPerformed

    private void cmbGastosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbGastosActionPerformed
        /*String Concepto=cmbGastos.getSelectedItem().toString();
        String Tipo="", Descripcion="", Monto="";
        String sql;
        String[] datos=new String[4];
        ResultSet rs;
        Statement st;
        sql="SELECT GASTOS_TIPO, GASTOS_MONTO, GASTOS_DESCRIPCION "
        + " FROM peleteriacid.gastos WHERE GASTOS_CONCEPTO = '"+Concepto+"';";
        try {
            st=cn.createStatement();
            rs=st.executeQuery(sql);

            while (rs.next()){
                datos[0]=Concepto;
                datos[1]=rs.getString(1);
                datos[2]=String.valueOf(rs.getDouble(2));
                datos[3]=rs.getString(3);
            }
            rs.close();
            modelo1.addRow(datos);
            tblGastos.setModel(modelo1);
        }catch(SQLException ex){
            Logger.getLogger(RegistrarVenta.class.getName()).log(Level.SEVERE, null, ex);
        }*/
    }//GEN-LAST:event_cmbGastosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CorteCajaMes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CorteCajaMes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CorteCajaMes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CorteCajaMes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CorteCajaMes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCorte;
    private javax.swing.JComboBox<String> cmbGastofijo;
    private javax.swing.JComboBox<String> cmbGastos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tblGastos;
    private javax.swing.JTable tblTabla;
    // End of variables declaration//GEN-END:variables
}
