/*

 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Paquete;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import java.text.Format;
import java.util.Date;
import java.util.Calendar;
import java.text.DateFormat;
import java.text.ParseException;
import javax.swing.JOptionPane;
/**
 *
 * @author Gloria
 */
public class Facturas extends javax.swing.JFrame {

    /**
     * Creates new form Facturas
     */
    
    public Facturas() {
        this.getContentPane().setBackground(Color.WHITE);
        initComponents();
        jScrollPane3.setVisible(false);
        ConsDatos();
    }
    public void ConsDatos(){
        DefaultTableModel modelo=new DefaultTableModel();
        modelo.addColumn("Fecha de factura");
        modelo.addColumn("Proveedor");
        modelo.addColumn("No. Factura");
        modelo.addColumn("Subtotal");
        modelo.addColumn("Descuento");
        modelo.addColumn("IVA");
        modelo.addColumn("Total");
        modelo.addColumn("Estatus");
        modelo.addColumn("Método de pago");
        
        tblCortes.setModel(modelo);
        String sql;
        ResultSet rs;
        Statement st;
        String[] datos=new String[9];
        
            sql="SELECT FACTURA_FECHA, FACTURA_PROVEEDOR, FACTURA_NUMERO, FACTURA_SUBTOTAL, FACTURA_DESCUENTO, FACTURA_IVA, FACTURA_TOTAL, FACTURA_ESTATUS, FACTURA_METODO"
                    + " FROM peleteriacid.facturas;";
        try {
            Format formatter = new SimpleDateFormat("yyyy-MM-dd");
            st=cn.createStatement();
            rs=st.executeQuery(sql);
            
            while (rs.next()){
                
                datos[0]=formatter.format(rs.getDate(1));
                datos[1]=rs.getString(2);
                datos[2]=rs.getString(3);
                datos[3]=String.valueOf(rs.getDouble(4));
                datos[4]=String.valueOf(rs.getDouble(5));
                datos[5]=String.valueOf(rs.getDouble(6));
                datos[6]=String.valueOf(rs.getDouble(7));
                datos[7]=rs.getString(8);
                datos[8]=rs.getString(9);
                modelo.addRow(datos);
            }
            tblCortes.setModel(modelo);
            rs.close();
            
        }catch(SQLException ex){
            Logger.getLogger(Facturas.class.getName()).log(Level.SEVERE, null, ex);
        }
        DefaultTableModel modelito=new DefaultTableModel();
        modelito.addColumn("Fac-ID");
        tblIndices.setModel(modelito);
        String[] datos1=new String[1];
        sql="SELECT FACTURA_ID"
                    + " FROM peleteriacid.facturas;";
        try {
            st=cn.createStatement();
            rs=st.executeQuery(sql);
            while (rs.next()){
                
                datos1[0]=String.valueOf(rs.getInt(1));
                modelito.addRow(datos1);
            }
            tblIndices.setModel(modelito);
            rs.close();
        }catch(SQLException ex){
            Logger.getLogger(Facturas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        Listar = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCortes = new javax.swing.JTable();
        btnListar = new javax.swing.JButton();
        dateFecha = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMateriales = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        dateFecha1 = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblIndices = new javax.swing.JTable();

        Listar.setText("Descripción");
        Listar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarActionPerformed(evt);
            }
        });
        jPopupMenu1.add(Listar);

        jMenuItem1.setText("Marcar como Pagada");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 204));
        jLabel9.setText("LISTA DE FACTURAS");

        tblCortes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblCortes.setComponentPopupMenu(jPopupMenu1);
        jScrollPane1.setViewportView(tblCortes);

        btnListar.setText("Listar");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        jLabel1.setText("Escoja una fecha inicial:");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Descripcion"));

        tblMateriales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblMateriales);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jLabel2.setText("Clic derecho para mas informacion de esta factura");

        jLabel3.setText("Escoja una fecha final:");

        tblIndices.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblIndices);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(102, 102, 102))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(dateFecha1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(29, 29, 29)
                                .addComponent(dateFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(143, 143, 143)
                        .addComponent(btnListar)
                        .addGap(42, 42, 42))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 641, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(22, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel2))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(dateFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addGap(297, 297, 297))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(dateFecha1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnListar)
                                .addGap(35, 35, 35)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        Format formatter = new SimpleDateFormat("yyyy-MM-dd");
        String fecha=formatter.format(dateFecha.getDate());
        String fecha1=formatter.format(dateFecha1.getDate());
        DefaultTableModel modelo=new DefaultTableModel();
        modelo.addColumn("Fecha de factura");
        modelo.addColumn("Proveedor");
        modelo.addColumn("No. Factura");
        modelo.addColumn("Subtotal");
        modelo.addColumn("Descuento");
        modelo.addColumn("IVA");
        modelo.addColumn("Total");
        modelo.addColumn("Estatus");
        modelo.addColumn("Método de pago");
        tblCortes.setModel(modelo);
        String sql;
        ResultSet rs;
        Statement st;
        String[] datos=new String[9];
        
           sql="SELECT FACTURA_FECHA, FACTURA_PROVEEDOR, FACTURA_NUMERO, FACTURA_SUBTOTAL, FACTURA_DESCUENTO, FACTURA_IVA, FACTURA_TOTAL, FACTURA_ESTATUS, FACTURA_METODO"
                    + " FROM peleteriacid.facturas WHERE FACTURA_FECHA BETWEEN '"+fecha+"' AND '"+fecha1+"';";
        try {
            st=cn.createStatement();
            rs=st.executeQuery(sql);
            System.out.println(sql);
            while (rs.next()){
                datos[0]=formatter.format(rs.getDate(1));
                datos[1]=rs.getString(2);
                datos[2]=rs.getString(3);
                datos[3]=String.valueOf(rs.getDouble(4));
                datos[4]=String.valueOf(rs.getDouble(5));
                datos[5]=String.valueOf(rs.getDouble(6));
                datos[6]=String.valueOf(rs.getDouble(7));
                datos[7]=rs.getString(8);
                datos[8]=rs.getString(9);
                modelo.addRow(datos);
            }
            tblCortes.setModel(modelo);
            rs.close();
            
        }catch(SQLException ex){
            Logger.getLogger(Facturas.class.getName()).log(Level.SEVERE, null, ex);
        }
        DefaultTableModel modelito=new DefaultTableModel();
        modelito.addColumn("Fac-ID");
        tblIndices.setModel(modelito);
        String[] datos1=new String[1];
        sql="SELECT FACTURA_ID"
                    + " FROM peleteriacid.facturas WHERE FACTURA_FECHA BETWEEN '"+fecha+"' AND '"+fecha1+"';";
        try {
            st=cn.createStatement();
            rs=st.executeQuery(sql);
            while (rs.next()){
                
                datos1[0]=String.valueOf(rs.getInt(1));
                modelito.addRow(datos1);
            }
            tblIndices.setModel(modelito);
            rs.close();
        }catch(SQLException ex){
            Logger.getLogger(Facturas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnListarActionPerformed

    private void ListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarActionPerformed
        int row=tblCortes.getSelectedRow();
        if(row>=0){
            int ID=0;
            String NUMERO=tblIndices.getValueAt(row,0).toString();
            
            int Materia=0, Cantidad=0;
            double Costo=0.0;
            DefaultTableModel modelito=new DefaultTableModel();
            modelito.addColumn("SKU");
            modelito.addColumn("Tipo");
            modelito.addColumn("Modelo");
            modelito.addColumn("Color");
            modelito.addColumn("Adquirido (pzas)");
            modelito.addColumn("Total");
            tblMateriales.setModel(modelito);
            
                ID=Integer.parseInt(NUMERO);
                String[] datos=new String[6];
                ResultSet rs1;
                Statement st1;
                try{
                    String sql1=("SELECT MATERIA_ID, MATERIA_CANTIDAD, MATERIA_COSTO FROM peleteriacid.materiales_has_facturas "
                +"WHERE FACTURA_ID = '"+ID+"';");
                st1=cn.createStatement();
                rs1=st1.executeQuery(sql1);
                    while (rs1.next()){
                        ResultSet rs2;
                        Statement st2;
                        Materia=rs1.getInt(1);
                        datos[4]=String.valueOf(rs1.getInt(2));
                        datos[5]=String.valueOf(rs1.getDouble(3));
                                try{
                                String sql2=("SELECT MATERIA_SKU, MATERIA_TIPO, MATERIA_MODELO, MATERIA_COLOR FROM peleteriacid.materiales "
                                    +"WHERE MATERIA_ID = '"+Materia+"';");
                                    st2=cn.createStatement();
                                    rs2=st2.executeQuery(sql2);
                                        while (rs2.next()){
                                            datos[0]=rs2.getString(1);
                                            datos[1]=rs2.getString(2);
                                            datos[2]=rs2.getString(3);
                                            datos[3]=rs2.getString(4);
                                        }
                                rs2.close();
                                tblMateriales.setModel(modelito);
                                    }catch(SQLException ex){
                                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                                    }
                        modelito.addRow(datos);
                    }
                    rs1.close();
                    tblMateriales.setModel(modelito);
                        }catch(SQLException ex){
                    Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                }
        }else{
            JOptionPane.showMessageDialog(null, "No seleccionó ninguna fila");
        }
    }//GEN-LAST:event_ListarActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        int row=tblCortes.getSelectedRow();
        if(row>=0){
            String NUMERO=tblIndices.getValueAt(row,0).toString();
            String Estado=tblCortes.getValueAt(row, 7).toString();
            if(Estado.equals("Pendiente")){
                String Metodo=JOptionPane.showInputDialog(this, "Escriba el metodo de pago: ");
                if(Metodo!=null||!Metodo.equals("")){
                    try{
                        PreparedStatement pst1=cn.prepareStatement("UPDATE peleteriacid.facturas "
                        +"SET FACTURA_ESTATUS = 'Pagado', FACTURA_METODO = '"+Metodo+"' WHERE FACTURA_NUMERO = '"+NUMERO
                        +"';");
                        System.out.println(pst1);
                        pst1.executeUpdate();
                        ConsDatos();
                    }catch(SQLException ex){
                        Logger.getLogger(AgregarMaterial.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }else{

                }
            }else{
                JOptionPane.showMessageDialog(this, "Esta factura ya fué pagada");
            }
        }else{
            JOptionPane.showMessageDialog(this, "No seleccionó ninguna fila");
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Facturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Facturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Facturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Facturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Facturas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Listar;
    private javax.swing.JButton btnListar;
    private com.toedter.calendar.JDateChooser dateFecha;
    private com.toedter.calendar.JDateChooser dateFecha1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblCortes;
    private javax.swing.JTable tblIndices;
    private javax.swing.JTable tblMateriales;
    // End of variables declaration//GEN-END:variables
Conectar cc=new Conectar();
Connection cn=cc.conexion();
}
