/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Paquete;
import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.Format;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gloria
 */
public class ListarCortes extends javax.swing.JFrame {

    /**
     * Creates new form ListarCortes
     */
    
    public ListarCortes() {
        this.getContentPane().setBackground(Color.WHITE);
        initComponents();
        /*
        DefaultTableModel modelo=new DefaultTableModel();
        modelo.addColumn("Fecha");
        modelo.addColumn("Ingresos");
        modelo.addColumn("Egresos");
        modelo.addColumn("Monto final");
        tblCortes.setModel(modelo);
        String sql;
        ResultSet rs;
        Statement st;
        String[] datos=new String[4];
        
            sql="SELECT *"
                    + " FROM peleteriacid.cortecaja_dias;";
        try {
            Format formatter = new SimpleDateFormat("yyyy-MM-dd");
            st=cn.createStatement();
            rs=st.executeQuery(sql);
            
            while (rs.next()){
                datos[0]=formatter.format(rs.getDate(1));
                datos[1]=String.valueOf(rs.getDouble(2));
                datos[2]=String.valueOf(rs.getDouble(3));
                datos[3]=String.valueOf(rs.getDouble(4));
                modelo.addRow(datos);
            }
            tblCortes.setModel(modelo);
            rs.close();
            
        }catch(SQLException ex){
            Logger.getLogger(ListarMateriales.class.getName()).log(Level.SEVERE, null, ex);
        }
        */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateFecha = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnListar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblVentas = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblGastos = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Ventas = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Realizo = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Balance = new javax.swing.JLabel();
        Ganancias = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Escoja una fecha:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 204));
        jLabel9.setText("LISTA DE CORTES");

        btnListar.setText("Listar");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        tblVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblVentas);

        tblGastos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblGastos);

        jLabel2.setFont(new java.awt.Font("Sylfaen", 2, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 0, 51));
        jLabel2.setText("Ventas realizadas:");

        jLabel3.setFont(new java.awt.Font("Sylfaen", 2, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 0, 51));
        jLabel3.setText("Gastos realizados:");

        jLabel4.setFont(new java.awt.Font("Sylfaen", 2, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 204));
        jLabel4.setText("Ganancias totales:");

        jLabel5.setFont(new java.awt.Font("Sylfaen", 2, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 204));
        jLabel5.setText("Ventas totales:");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Paquete/LogoPeleteria.png"))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Sylfaen", 2, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 204));
        jLabel7.setText("Realizó:");

        Realizo.setFont(new java.awt.Font("Sylfaen", 2, 14)); // NOI18N
        Realizo.setForeground(new java.awt.Color(0, 102, 204));

        jLabel8.setFont(new java.awt.Font("Sylfaen", 2, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 204));
        jLabel8.setText("Balance:");

        Balance.setFont(new java.awt.Font("Sylfaen", 2, 14)); // NOI18N
        Balance.setForeground(new java.awt.Color(0, 102, 204));

        Ganancias.setFont(new java.awt.Font("Sylfaen", 2, 14)); // NOI18N
        Ganancias.setForeground(new java.awt.Color(0, 102, 204));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(196, 196, 196)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(Ventas, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Ganancias, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(116, 116, 116))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel6)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(29, 29, 29)
                                    .addComponent(dateFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(Balance, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnListar)
                                .addGap(158, 158, 158))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(Realizo, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(205, 205, 205))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(dateFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1))
                            .addComponent(btnListar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(Ventas, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Ganancias, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Realizo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(Balance, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        Format formatter = new SimpleDateFormat("yyyy-MM-dd");
        String fecha=formatter.format(dateFecha.getDate());
        System.out.println(fecha);
        Double Total=0.0, Ganancias=0.0;
        String Realizo = "";
        ResultSet rs;
        Statement st;
        //tblCortes.setModel(modelo);
        try{
        String sql=("SELECT * FROM cortecaja_dias "
            +"WHERE CORTEDIA_FECHA = '"+fecha+"';");
        
            
            System.out.println(sql);
            st=cn.createStatement();
            rs=st.executeQuery(sql);

                while (rs.next()){
                        String[] datos1=new String[3];
                        DefaultTableModel modelote=new DefaultTableModel();
                        modelote.addColumn("Fecha");
                        modelote.addColumn("Metodo de pago");
                        modelote.addColumn("Total");
                        tblVentas.setModel(modelote);
                        ResultSet rs1;
                        Statement st1;
                        try{
                            
                            String sql1=("SELECT * FROM peleteriacid.pedidos "
                                +"WHERE PEDIDO_FECHA = '"+fecha+"';");
                            st1=cn.createStatement();
                            rs1=st1.executeQuery(sql1);
                               System.out.println(sql1);
                            while (rs1.next()){
                                datos1[0]=formatter.format(rs1.getDate(3));
                                datos1[1]=rs1.getString(4);
                                datos1[2]=String.valueOf(rs1.getDouble(2));
                                modelote.addRow(datos1);
                            }
                            tblVentas.setModel(modelote);
                            rs1.close();
                        }catch(SQLException ex){
                            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        ResultSet rs2;
                        Statement st2;
                        try{
                            String sql2=("SELECT * FROM peleteriacid.cortecaja_dias_has_gastos "
                                +"WHERE CORTEDIA_FECHA = '"+fecha+"';");
                            st2=cn.createStatement();
                            rs2=st2.executeQuery(sql2);
                               System.out.println(sql2);
                               String[] datos2=new String[4];
                                DefaultTableModel modelote2=new DefaultTableModel();
                                modelote2.addColumn("Tipo");
                                modelote2.addColumn("Monto");
                                modelote2.addColumn("Descripcion");
                                modelote2.addColumn("Total");
                                tblGastos.setModel(modelote2);
                            while (rs2.next()){
                                int ID=rs2.getInt(2);
                                ResultSet rs3;
                                Statement st3;
                        try{
                            String sql3=("SELECT GASTOS_TIPO, GASTOS_MONTO, GASTOS_DESCRIPCION, GASTO_TOTAL FROM peleteriacid.gastos "
                                +"WHERE GASTOS_ID = '"+ID+"';");
                            st3=cn.createStatement();
                            rs3=st3.executeQuery(sql3);
                               System.out.println(sql3);
                                
                            while (rs3.next()){
                                datos2[0]=rs3.getString(1);
                                datos2[1]=String.valueOf(rs3.getDouble(2));
                                datos2[2]=rs3.getString(3);
                                datos2[3]=String.valueOf(rs3.getDouble(4));
                                modelote2.addRow(datos2);
                            }
                            tblGastos.setModel(modelote2);
                            rs3.close();
                        }catch(SQLException ex){
                            Logger.getLogger(ListarCortes.class.getName()).log(Level.SEVERE, null, ex);
                        }
                                
                            }
                            rs2.close();
                        }catch(SQLException ex){
                            Logger.getLogger(ListarCortes.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    Total=rs.getDouble(2);
                    Realizo=rs.getString(5);
                    Ganancias=rs.getDouble(6);
                }
//                tblCortes.setModel(modelo);
                rs.close();
        }catch(SQLException ex){
            Logger.getLogger(ListarCortes.class.getName()).log(Level.SEVERE, null, ex);
        }
        int rows=tblGastos.getRowCount();
        int i=0;
        double Tota=0.0, Tot=0.0;
        while(i<rows){
           Tota=Double.parseDouble(tblGastos.getValueAt(i, 3).toString());
           Tot+=Tota;
        }
        this.Balance.setText(String.valueOf(Total-Tot));
        
        this.Realizo.setText(Realizo);
        Ventas.setText(Double.toString(Total));
        this.Ganancias.setText(String.valueOf(Ganancias));
    }//GEN-LAST:event_btnListarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListarCortes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListarCortes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListarCortes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListarCortes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListarCortes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Balance;
    private javax.swing.JLabel Ganancias;
    private javax.swing.JLabel Realizo;
    private javax.swing.JLabel Ventas;
    private javax.swing.JButton btnListar;
    private com.toedter.calendar.JDateChooser dateFecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblGastos;
    private javax.swing.JTable tblVentas;
    // End of variables declaration//GEN-END:variables
Conectar cc=new Conectar();
Connection cn=cc.conexion();
}
