/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Paquete;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.Format;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.text.ParseException;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Gloria
 */
public class RegistrarGasto extends javax.swing.JFrame {

    /**
     * Creates new form RegistrarGasto
     */
    public RegistrarGasto() {
        initComponents();
        LlenaCombo();
        jScrollPane2.setVisible(false);
        tblContenido.setVisible(false);
        cmbMetodo.setEnabled(false);
    }
    public void LimpiaCampos(){
        txtConcepto.setText("");
        txtMonto.setText("");
        txtDescripcion.setText("");
        cmbTipo.setSelectedIndex(0);
        cmbMetodo.setSelectedIndex(0);
        txtTotal.setText("");
        dateGastos.setCalendar(null);
        chkIVA.setSelected(false);
        cmbPagado.setSelectedIndex(0);
    }
    private void LlenaCombo(){
        String sql="SELECT * FROM peleteriacid.proveedores WHERE PROV_TIPO = 'Servicios';";
        ResultSet rs;
        Statement st;
        try{
            st=cn.createStatement();
            rs=st.executeQuery(sql);
            
            while (rs.next()){
                
                String ClaveInst=rs.getString(2);
                cmbProveedores.addItem(ClaveInst);
            }
        }catch(SQLException ex){
            Logger.getLogger(AgregarMaterial.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        txtConcepto = new javax.swing.JTextField();
        cmbTipo = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        txtMonto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        chkIVA = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        dateGastos = new com.toedter.calendar.JDateChooser();
        cmbMetodo = new javax.swing.JComboBox<>();
        cmbPagado = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        cmbProveedores = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblContenido = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 204));
        jLabel9.setText("REGISTRO DE GASTOS");

        cmbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Seleccione el tipo>", "Administración", "Venta", "Diversos" }));

        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        jScrollPane1.setViewportView(txtDescripcion);

        jLabel1.setText("Tipo de gasto:");

        txtMonto.setEnabled(false);
        txtMonto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMontoKeyReleased(evt);
            }
        });

        jLabel2.setText("Concepto:");

        jLabel3.setText("Subtotal:");

        jLabel4.setText("Descripcion:");

        jLabel5.setText("$");

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        chkIVA.setText("IVA");
        chkIVA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkIVAActionPerformed(evt);
            }
        });

        jLabel6.setText("Total:");

        txtTotal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTotalKeyReleased(evt);
            }
        });

        jLabel10.setText("Fecha:");

        cmbMetodo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Método de pago>", "Efectivo", "Tarjeta de crédito", "Transferencia Electrónica" }));

        cmbPagado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Seleccione>", "Sí", "No" }));
        cmbPagado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPagadoActionPerformed(evt);
            }
        });

        jLabel7.setText("Pagado:");

        cmbProveedores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Seleccione un Proveedor>" }));
        cmbProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbProveedoresActionPerformed(evt);
            }
        });
        cmbProveedores.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cmbProveedoresPropertyChange(evt);
            }
        });

        jLabel11.setText("Proveedor:");

        tblContenido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblContenido.setEnabled(false);
        jScrollPane2.setViewportView(tblContenido);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                                        .addComponent(txtConcepto, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel10))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(dateGastos, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cmbTipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGap(73, 73, 73)
                                .addComponent(jLabel7)
                                .addGap(33, 33, 33)
                                .addComponent(cmbPagado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(34, 34, 34)
                                        .addComponent(cmbProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnRegistrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(chkIVA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(202, 202, 202))
                            .addComponent(cmbMetodo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(37, 37, 37)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel1)
                                            .addComponent(cmbPagado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7))
                                        .addGap(28, 28, 28)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(dateGastos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel10)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cmbMetodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(txtConcepto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3)
                                    .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chkIVA)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(cmbProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel11)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        int met=cmbMetodo.getSelectedIndex();
        if(met!=0){
        String Nombre=txtConcepto.getText(), Notas="";
        double monto=Double.parseDouble(txtMonto.getText()), Total=Double.parseDouble(txtTotal.getText());
        boolean[] field = new boolean[1];
        field[0]=txtDescripcion.getText().isEmpty();
        
        if(!field[0]){
            Notas=txtDescripcion.getText();
        }
        String Metodo=cmbMetodo.getSelectedItem().toString();
        String Tipo=cmbTipo.getSelectedItem().toString();
        double IVA=0.0;
        if(chkIVA.isSelected()==true){
               IVA=Total-monto;
        }
        String PAGADO=cmbPagado.getSelectedItem().toString();
        if(PAGADO.equals("No"))
            Metodo="";
        int Option=JOptionPane.showOptionDialog(btnRegistrar, 
                    "\nConcepto: "+Nombre
                        + "\nTipo: "+Tipo
                            +"\nMonto: "+monto
                                +"\nTotal: "+Total
                                    +"\nMetodo de pago: "+Metodo
        + "\n¿Es correcto?","Confirme el registro",JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, new Object[]{"Si","No"},"Si");
            if(Option==0){
                
              try{
                  DateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
                Date utilDate;
                utilDate = new SimpleDateFormat("dd-MM-yyyy").parse(dateFormat.format(dateGastos.getDate()));
                java.sql.Date sqlDate1 = new java.sql.Date(utilDate.getTime());
                
                  PreparedStatement pst =cn.prepareStatement("INSERT INTO peleteriacid.gastos(GASTOS_CONCEPTO, GASTOS_TIPO, GASTOS_MONTO, GASTOS_DESCRIPCION, GASTO_IVA, GASTO_FECHA, GASTO_TOTAL, GASTO_METODO, GASTO_PAGADO)"
                      +" VALUES ( ?, ?, ?, ?, ?, ?, ?, ?, ? );");
                  pst.setString(1, Nombre);
                  pst.setString(2, Tipo);
                  pst.setDouble(3, monto);
                  pst.setString(4, Notas);
                  pst.setDouble(5, IVA);
                  pst.setDate(6, sqlDate1);
                  pst.setDouble(7, Total);
                  pst.setString(8, Metodo);
                  pst.setString(9, PAGADO);
                  System.out.println(pst);
                  pst.executeUpdate();
                  JOptionPane.showMessageDialog(this, "El registro fué hecho con éxito");
                  LimpiaCampos();
              }catch(SQLException ex){
                  Logger.getLogger(RegistrarGasto.class.getName()).log(Level.SEVERE, null, ex);
              }catch (ParseException ex) {
            Logger.getLogger(RegistrarGasto.class.getName()).log(Level.SEVERE, null, ex);
        }
              if(cmbProveedores.getSelectedIndex()!=0){
              //Recorrido de id
              DefaultTableModel modelo=new DefaultTableModel();
        modelo.addColumn("ID");
        tblContenido.setModel(modelo);
        String sql;
        ResultSet rs;
        Statement st;
        String[] datos=new String[10];
          sql="SELECT GASTOS_ID FROM peleteriacid.gastos ORDER BY GASTOS_ID DESC;";
          
        try {
            st=cn.createStatement();
            rs=st.executeQuery(sql);
            System.out.println(sql);
            
            while (rs.next()){
                datos[0]=String.valueOf(rs.getInt(1));
                modelo.addRow(datos);
            }
            tblContenido.setModel(modelo);
            rs.close();
            }catch(SQLException ex){
            Logger.getLogger(AgregarMaterial.class.getName()).log(Level.SEVERE, null, ex);
        }   
            int relacion=Integer.parseInt(tblContenido.getValueAt(0, 0).toString());
        //Wait up
              String Proveedor=cmbProveedores.getSelectedItem().toString();
              sql="SELECT * FROM peleteriacid.proveedores WHERE PROV_NOMBRE = '"+Proveedor+"';";
        String IDProveedor="";
        try{
            st=cn.createStatement();
            rs=st.executeQuery(sql);
            
            while (rs.next()){
                IDProveedor=Integer.toString(rs.getInt(1));
            }
            
            System.out.println("Id del proveedor con el nombre "+Proveedor+" es: "+IDProveedor);
        }catch(SQLException ex){
            Logger.getLogger(AgregarMaterial.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        int id=Integer.parseInt(IDProveedor);
        try{
        PreparedStatement pst =cn.prepareStatement("INSERT INTO peleteriacid.gastos_has_proveedores(GASTOS_ID, PROV_ID)"
            +" VALUES ( ?, ?);");
        pst.setInt(1, relacion);
        pst.setInt(2, id);
        System.out.println(pst);
        pst.executeUpdate();
        }catch(SQLException ex){
        Logger.getLogger(AgregarMaterial.class.getName()).log(Level.SEVERE, null, ex);
        }
              }else{
                  
              }
        //Final de la asignacion de proveedores
            }else{

            }
        }else{
            JOptionPane.showMessageDialog(this, "Favor de introducir el método de pago");
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void chkIVAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkIVAActionPerformed
        double total= 0.0;
        boolean[] field=new boolean[1];
        field[0]=txtTotal.getText().isEmpty();
        if(!field[0]){
            total=Double.parseDouble(txtTotal.getText());
        }
        double subtotal = 0.0;
        if(chkIVA.isSelected()==true){
            subtotal=(total)/1.16;

        }else{
            subtotal=total;
        }
        txtMonto.setText(String.format("%.2f",(subtotal)));
    }//GEN-LAST:event_chkIVAActionPerformed

    private void txtMontoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMontoKeyReleased
        
    }//GEN-LAST:event_txtMontoKeyReleased

    private void txtTotalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTotalKeyReleased
        double total= Double.parseDouble(txtTotal.getText());
        
        double subtotal = 0.0;
        if(chkIVA.isSelected()==true){
            subtotal=(total)/1.16;

        }else{
            subtotal=total;
        }
        txtMonto.setText(String.format("%.2f",(subtotal)));
    }//GEN-LAST:event_txtTotalKeyReleased

    private void cmbProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbProveedoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbProveedoresActionPerformed

    private void cmbProveedoresPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cmbProveedoresPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbProveedoresPropertyChange

    private void cmbPagadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPagadoActionPerformed
        if(cmbPagado.getSelectedItem().equals("Sí")){
            cmbMetodo.setEnabled(true);
        }else{
            cmbMetodo.setEnabled(true);
            cmbMetodo.setSelectedIndex(0);
        }
    }//GEN-LAST:event_cmbPagadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarGasto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarGasto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarGasto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarGasto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarGasto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JCheckBox chkIVA;
    private javax.swing.JComboBox<String> cmbMetodo;
    private javax.swing.JComboBox<String> cmbPagado;
    private javax.swing.JComboBox<String> cmbProveedores;
    private javax.swing.JComboBox<String> cmbTipo;
    private com.toedter.calendar.JDateChooser dateGastos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblContenido;
    private javax.swing.JTextField txtConcepto;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtMonto;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
Conectar cc=new Conectar();
Connection cn=cc.conexion();
}
